contact_links:
  - name: 💬 YunYouJun's Discord Server
    url: https://discord.com/invite/nd3mPkU5j8
    about: Want to discuss / chat with the community? Here you go!
  - name: 💬 YunYouJun's QQ 群 1050458482
    url: https://qm.qq.com/cgi-bin/qm/qr?k=kZJzggTTCf4SpvEQ8lXWoi5ZjhAx0ILZ&jump_from=webapi
    about: 中文讨论
